export enum USUARIO_EVENTOS {
    "USUARIO_CRIAR" = "USUARIO_CRIAR",
    "USUARIO_EDITAR" = "USUARIO_EDITAR",
    "USUARIO_EXCLUIR" = "USUARIO_EXCLUIR",
    "USUARIO_ATIVAR" = "USUARIO_ATIVAR",
    "USUARIO_DESATIVAR" = "USUARIO_DESTATIVAR"
}


export enum FUNCAO_EVENTOS {
    "FUNCAO_CRIAR" = "FUNCAO_CRIAR",
    "FUNCAO_EDITAR" = "FUNCAO_EDITAR",
    "FUNCAO_EXCLUIR" = "FUNCAO_EXCLUIR",
    "FUNCAO_ATIVAR" = "FUNCAO_ATIVAR",
    "FUNCAO_DESATIVAR" = "FUNCAO_DESTATIVAR"
}


export enum EQUIPAMENTOS_EVENTOS {
    "EQP_CRIAR" = "EQP_CRIAR",
    "EQP_EDITAR" = "EQP_EDITAR",
    "EQP_EXCLUIR" = "EQP_EXCLUIR",
    "EQP_ATIVAR" = "EQP_ATIVAR",
    "EQP_DESATIVAR" = "EQP_DESTATIVAR"
}


export enum FABRICANTE_EVENTOS {
    "FABRICANTE_CRIAR" = "FABRICANTE_CRIAR",
    "FABRICANTE_EDITAR" = "FABRICANTE_EDITAR",
    "FABRICANTE_EXCLUIR" = "FABRICANTE_EXCLUIR",
    "FABRICANTE_ATIVAR" = "FABRICANTE_ATIVAR",
    "FABRICANTE_DESATIVAR" = "FABRICANTE_DESTATIVAR"
}

export enum FORMULARIO {
    "NENHUM" = "NENHUM",
    "PRODUTO" = "PRODUTO",
    "GRUPO" = "GRUPO",
    "SUB_GRUPO" = "SUB_GRUPO",
}
export enum EVENTO {
    "NENHUM" = "NENHUM",
    "CRIAR" = "CRIAR",
    "EDITAR" = "EDITAR",
    "EXCLUIR" = "EXCLUIR",
    "ATIVA" = "ATIVA",
    "DESTATIVAR" = "DESATIVAR",
    "FILTRAR" = "FILTRAR"
}