export enum PESSOA_EVENTOS {
    "PESSOA_CRIAR" = "PESSOA_CRIAR",
    "PESSOA_EDITAR" = "PESSOA_EDITAR",
    "PESSOA_EXCLUIR" = "PESSOA_EXCLUIR",
    "PESSOA_ATIVAR" = "PESSOA_ATIVAR",
    "PESSOA_DESATIVAR" = "PESSOA_DESTATIVAR"
}


export enum ENDERECOS_EVENTOS {
    "ENDERECOS_CRIAR" = "ENDERECOS_CRIAR",
    "ENDERECOS_EDITAR" = "ENDERECOS_EDITAR",
    "ENDERECOS_EXCLUIR" = "ENDERECOS_EXCLUIR",
    "ENDERECOS_ATIVAR" = "ENDERECOS_ATIVAR",
    "ENDERECOS_DESATIVAR" = "ENDERECOS_DESTATIVAR"
}


export enum CONTATO_EVENTOS {
    "CONTATRO_CRIAR" = "CONTATRO_CRIAR",
    "CONTATRO_EDITAR" = "CONTATRO_EDITAR",
    "CONTATRO_EXCLUIR" = "CONTATRO_EXCLUIR",
    "CONTATRO_ATIVAR" = "CONTATRO_ATIVAR",
    "CONTATRO_DESATIVAR" = "CONTATRO_DESTATIVAR"
}

export enum FORMULARIO {
    "NENHUM" = "NENHUM",
    "PESSOA" = "PESSOA",
    "ENDERECO" = "ENDERECO",
    "CONTATO" = "CONTATO",
    "PSQ_AVANCADO" = "PSQ_AVANCADO",
}
export enum EVENTO {
    "NENHUM" = "NENHUM",
    "CRIAR" = "CRIAR",
    "EDITAR" = "EDITAR",
    "EXCLUIR" = "EXCLUIR",
    "ATIVA" = "ATIVA",
    "DESTATIVAR" = "DESATIVAR",
    "FILTRAR" = "FILTRAR"
}


export enum SUB_DOMINIO {
    "NEBGUM" = "NENHUM",
    "VISAO" = "VISAO",
    "PESSOA" = "PESSOA",
    "ENDERECO" = "ENDERECO",
    "CONTATO" = "CONTATO",
}

export interface IMesaDominio {
    index: number,
    janela: string,
    titulo: string,
    subDominio: SUB_DOMINIO
}