/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIndexRouteImport } from './routes/produto/index'
import { Route as PessoaIndexRouteImport } from './routes/pessoa/index'
import { Route as CompraIndexRouteImport } from './routes/compra/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIndexRoute = ProdutoIndexRouteImport.update({
  id: '/produto/',
  path: '/produto/',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoaIndexRoute = PessoaIndexRouteImport.update({
  id: '/pessoa/',
  path: '/pessoa/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompraIndexRoute = CompraIndexRouteImport.update({
  id: '/compra/',
  path: '/compra/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compra': typeof CompraIndexRoute
  '/pessoa': typeof PessoaIndexRoute
  '/produto': typeof ProdutoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compra': typeof CompraIndexRoute
  '/pessoa': typeof PessoaIndexRoute
  '/produto': typeof ProdutoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compra/': typeof CompraIndexRoute
  '/pessoa/': typeof PessoaIndexRoute
  '/produto/': typeof ProdutoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compra' | '/pessoa' | '/produto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compra' | '/pessoa' | '/produto'
  id: '__root__' | '/' | '/compra/' | '/pessoa/' | '/produto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompraIndexRoute: typeof CompraIndexRoute
  PessoaIndexRoute: typeof PessoaIndexRoute
  ProdutoIndexRoute: typeof ProdutoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/': {
      id: '/produto/'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoa/': {
      id: '/pessoa/'
      path: '/pessoa'
      fullPath: '/pessoa'
      preLoaderRoute: typeof PessoaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compra/': {
      id: '/compra/'
      path: '/compra'
      fullPath: '/compra'
      preLoaderRoute: typeof CompraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompraIndexRoute: CompraIndexRoute,
  PessoaIndexRoute: PessoaIndexRoute,
  ProdutoIndexRoute: ProdutoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
