/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIndexRouteImport } from './routes/produto/index'
import { Route as CompraIndexRouteImport } from './routes/compra/index'
import { Route as ProdutoProdutoRouteImport } from './routes/produto/produto'
import { Route as ProdutoNavRouteImport } from './routes/produto/nav'
import { Route as ProdutoGrupoRouteImport } from './routes/produto/grupo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIndexRoute = ProdutoIndexRouteImport.update({
  id: '/produto/',
  path: '/produto/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompraIndexRoute = CompraIndexRouteImport.update({
  id: '/compra/',
  path: '/compra/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoProdutoRoute = ProdutoProdutoRouteImport.update({
  id: '/produto/produto',
  path: '/produto/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoNavRoute = ProdutoNavRouteImport.update({
  id: '/produto/nav',
  path: '/produto/nav',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoGrupoRoute = ProdutoGrupoRouteImport.update({
  id: '/produto/grupo',
  path: '/produto/grupo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/produto/grupo': typeof ProdutoGrupoRoute
  '/produto/nav': typeof ProdutoNavRoute
  '/produto/produto': typeof ProdutoProdutoRoute
  '/compra': typeof CompraIndexRoute
  '/produto': typeof ProdutoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produto/grupo': typeof ProdutoGrupoRoute
  '/produto/nav': typeof ProdutoNavRoute
  '/produto/produto': typeof ProdutoProdutoRoute
  '/compra': typeof CompraIndexRoute
  '/produto': typeof ProdutoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/produto/grupo': typeof ProdutoGrupoRoute
  '/produto/nav': typeof ProdutoNavRoute
  '/produto/produto': typeof ProdutoProdutoRoute
  '/compra/': typeof CompraIndexRoute
  '/produto/': typeof ProdutoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/produto/grupo'
    | '/produto/nav'
    | '/produto/produto'
    | '/compra'
    | '/produto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/produto/grupo'
    | '/produto/nav'
    | '/produto/produto'
    | '/compra'
    | '/produto'
  id:
    | '__root__'
    | '/'
    | '/produto/grupo'
    | '/produto/nav'
    | '/produto/produto'
    | '/compra/'
    | '/produto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProdutoGrupoRoute: typeof ProdutoGrupoRoute
  ProdutoNavRoute: typeof ProdutoNavRoute
  ProdutoProdutoRoute: typeof ProdutoProdutoRoute
  CompraIndexRoute: typeof CompraIndexRoute
  ProdutoIndexRoute: typeof ProdutoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/': {
      id: '/produto/'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compra/': {
      id: '/compra/'
      path: '/compra'
      fullPath: '/compra'
      preLoaderRoute: typeof CompraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/produto': {
      id: '/produto/produto'
      path: '/produto/produto'
      fullPath: '/produto/produto'
      preLoaderRoute: typeof ProdutoProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/nav': {
      id: '/produto/nav'
      path: '/produto/nav'
      fullPath: '/produto/nav'
      preLoaderRoute: typeof ProdutoNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/grupo': {
      id: '/produto/grupo'
      path: '/produto/grupo'
      fullPath: '/produto/grupo'
      preLoaderRoute: typeof ProdutoGrupoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProdutoGrupoRoute: ProdutoGrupoRoute,
  ProdutoNavRoute: ProdutoNavRoute,
  ProdutoProdutoRoute: ProdutoProdutoRoute,
  CompraIndexRoute: CompraIndexRoute,
  ProdutoIndexRoute: ProdutoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
